# Generated by Django 3.0.1 on 2019-12-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='datafile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
