# Generated by Django 3.0.1 on 2020-01-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaInfo',
            fields=[
                ('media_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('media_size', models.IntegerField()),
                ('datafile', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
