# Generated by Django 3.0.1 on 2020-01-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadInfo',
            fields=[
                ('user_email', models.EmailField(max_length=40)),
                ('media_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('media_size', models.IntegerField()),
                ('viewed_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
